### ISSUE TITLE
QoL: Automatically fill certain MDB text_data_dict categories using translations from other categories

### ISSUE THREAD

**Issue by KevinVG207** [Hachimi-Hachimi/ZokuZoku#3]
Certain categories are merely the same text as two other categories, concatenated or with a space in-between.
Examples:
* Outfit name + character name (4) is made up of outfit name (5) and character name (170 or 6).
* Support title + character name (75) is made up of support title (76) and character name (77).
(6, 77 and 170 have massive overlap too)

And then there are a couple categories that are trivial to generate automatically with code (at least for English) like birthdays (157) or things that simply need a character name inserted into a static string like character piece names (113).

Carotene's implementation for autofilling these and more can be seen here: https://github.com/KevinVG207/Uma-Carotene-TL/blob/main/src/autofill_mdb.py (ignore autofill_chara_story_chapters)

I don't know if you want this to be a part of Zokuzoku or separated from it (like me adapting the script from Carotene) and whether this could be something specific to the tl-en repo (or parts of it). Please let me know your thoughts.

**Comment by LeadRDRK** [comment]
~~If an entry can be generated from content that is expected to be typed in manually, then it could be automatically set whenever one of the dependencies changes; otherwise, the editor is not meant to do anything implicitly~~

**Comment by LeadRDRK** [comment]
I've just added a new feature in ac3bbb26a75c793973b13b79eb7e7097f66becf2 which lets you run specialized automation scripts (by running the "Run automation/Run all automations" commands in the command palette). These scripts must be in the TL repos themselves and are intended for this exact purpose. However, I've decided not to implement such a thing in the editor or directly in ZokuZoku; therefore this feature request is not actually fulfilled.

For the EN repo, I've added an autofill script for some of the things you mentioned in the `text_data` table. You can find it in [.vscode/zk_auto](https://github.com/Hachimi-Hachimi/tl-en/tree/dev/.vscode/zk_auto). Feel free to add more to the script if needed.

I will be documenting the API properly later but the type definitions are available in [docs/zk.d.ts](https://github.com/Hachimi-Hachimi/ZokuZoku/blob/main/docs/zk.d.ts) and also included in the `zk_auto` folder as `global.d.ts`, so there will be code suggestions and type checking when you edit the scripts in VSCode. Also, these scripts run in a sandboxed context so you won't be able to use anything aside from the standard JS functions and the `zk` module.

Closing as not implementing.
